theme: minima
title: null
author: CafeGeek

header_pages:
  - about.md
  - portfolio.md

header:
  image: /imagens/cafegeek_small.png


logo: imagens/cafegeek_small.png
title-img: imagens/cafegeek_small.png
tagline: CafeGeek

includes_dir  : _include
include       : _include

# Site Settings
breadcrumbs: true
sitemap: true
locale: "pt-br"
language: "pt-br"

# Remove button Github
github:
  is_project_page: false

defaults:
  - scope:
      path: "_include"
    values:
      sitemap:  false
  - scope:
      path: "google*"
    values:
      sitemap:  false

# --- Web Analytics Section --- #
gtag: "UA-74199518-1"
google_analytics: UA-74199518-1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
