theme: jekyll-theme-midnight
title: null
description: O CafeGeek é um site educacional com foco em desenvolvimento de jogos digitais e as disciplinas que orbitam este fantástico mundo
author:
  name: CafeGeek
  email: myerco@gmail.com
header_pages:
  - about.md
markdown: kramdown

header:
  image: /imagens/cafegeek_small.webp

minima:
  # generate social links in footer
  social_links:
    github: myerco
    youtube_channel: UCdP1V0cZN3TQOoBPBLuyhlQ
    youtube_channel_name: CafeGeek
    discord: 9jFmnV2S

logo: imagens/cafegeek_small.webp
title-img: imagens/cafegeek_small.webp
tagline: CafeGeek

includes_dir  : _include
include       : _include

# Site Settings
breadcrumbs: true
sitemap: true
locale: "pt-br"
language: "pt-br"

# Remove button Github
github:
  is_project_page: false

defaults:
  - scope:
      path: "_include"
    values:
      sitemap:  false
  - scope:
      path: "google*"
    values:
      sitemap:  false

# --- Web Analytics Section --- #
gtag: "UA-74199518-1"
google_analytics: UA-74199518-1

url: "https://cafegeek.eti.br/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
