# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "pt-BR"
title                    : Cafegeek
title_separator          : "|"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Cafegeek"
description              : "Site pessoal."
url                      : https://cafegeek.eti.br/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : /assets/images/cafegeek_small.webp # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true ##false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          :  lunr # lunr (default), algolia, google
lunr:
  search_within_pages    : true # true, false (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : #1ec807e2c495786f3 # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification : Y3i7BFqxyFTT6NzmAi7vPeR5eGwlveILhq8J9FbaTac
bing_site_verification   : "929EC82F8CA6637EEB2B56BD1004C0BF"
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : G-FKWKZK87NF
    anonymize_ip         : false # true, false (default)


# Site Author
author:
  name             : "Marco Yerco"
  avatar           : "/assets/images/profile_marco_yerco.webp"
  bio              : "Analista de sistemas e Professor."
  location         : "Porto Velho (RO), Brasil"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:cafegeekedu@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://cafegeek.eti.br"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/myerco"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/cafegeek.br/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCdP1V0cZN3TQOoBPBLuyhlQ"      
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marco-yerco-853333142/"            

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:


# Reading Files
include:
  - .htaccess
  - _pages
  - _docs
  - _jogatina
  - _me-conta-uma-historia
  - _unreal-engine  
  - _computacao-grafica
  - _a-taberna-do-ponei-saltitante
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections_dir: content
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  jogatina:
    output: true
    sort_by: order
    permalink: /:collection/:path/    
  me-conta-uma-historia:
    output: true
    sort_by: order
    permalink: /:collection/:path/
  unreal-engine:
    output: true
    sort_by: order
    permalink: /:collection/:path/    
  computacao-grafica:
    output: true
    permalink: /:collection/:path/        
  a-taberna-do-ponei-saltitante:    
    output: true
    permalink: /:collection/:path/              
  modelagem-3d:    
    output: true
    permalink: /:collection/:path/                  
  jogos-digitais:    
    output: true
    permalink: /:collection/:path/                      

imgpath: /assets/images/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      toc: true        
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      share: true
      #header:
      #  overlay_color: "#8c8c8c"
      #  teaser: /assets/images/unreal/unreal_engine.webp
  # _docs
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: single
      read_time: true
      author_profile: true
      share: false
      comments: false
  # Jogatina           
  - scope:
      path: "_jogatina"
      type: jogatina
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true
      show_date: true
      sort_by: order            
      category: "Desenvolvimento de jogos digitais"                  
      toc: true
      sidebar:
        nav: dev_jogatina 
# Me conta uma história
  - scope:
      path: "_me-conta-uma-historia"
      type: "me-conta-uma-historia"
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true      
      show_date: true
      sort_by: order            
      category: "Desenvolvimento de jogos digitais"      
      toc: true
      sidebar:
        nav: dev_me_conta        
# Unreal Engine - Capítulo 1
  - scope:
      path: "_unreal-engine-capitulo-1"
      type: unreal-engine-capitulo-1
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true   
      sort_by: order            
      category: "Desenvolvimento de jogos digitais"
      sidebar:
        nav: dev_unreal_1
# Unreal Engine - Capítulo 2
  - scope:
      path: "_unreal-engine-capitulo-2"
      type: unreal-engine-capitulo-2
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true      
      sort_by: order            
      category: "Desenvolvimento de jogos digitais"
      sidebar:
        nav: dev_unreal_2      
# Unreal Engine - Capítulo 3
  - scope:
      path: "_unreal-engine-capitulo-3"
      type: unreal-engine-capitulo-3
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true
      sort_by: order            
      category: "Desenvolvimento de jogos digitais"
      sidebar:
        nav: dev_unreal_3      
# Unreal Engine - Capítulo 4
  - scope:
      path: "_unreal-engine-capitulo-4"
      type: unreal-engine-capitulo-4
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true  
      show_date: true
      toc: true      
      sort_by: order            
      category: "Desenvolvimento de jogos digitais"
      sidebar:
        nav: dev_unreal_4
# Unreal Engine - Capítulo 5
  - scope:
      path: "_unreal-engine-capitulo-5"
      type: unreal-engine-capitulo-5
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true
      show_date: true
      toc: true    
      sort_by: order            
      category: "Desenvolvimento de jogos digitais"
      sidebar:
        nav: dev_unreal_5  
# Unreal Engine - Capítulo 6
  - scope:
      path: "_unreal-engine-capitulo-6"
      type: unreal-engine-capitulo-6
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true  
      show_date: true
      toc: true   
      sort_by: order            
      category: "Desenvolvimento de jogos digitais"
      sidebar:
        nav: dev_unreal_6   
# Unreal Engine - Capítulo 7
  - scope:
      path: "_unreal-engine-capitulo-7"
      type: unreal-engine-capitulo-7
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true      
      sort_by: order            
      category: "Desenvolvimento de jogos digitais"
      sidebar:
        nav: dev_unreal_7
# Unreal Engine - Capítulo 8
  - scope:
      path: "_unreal-engine-capitulo-8"
      type: unreal-engine-capitulo-8
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true  
      sort_by: order      
      category: "Desenvolvimento de jogos digitais"
      sidebar:
        nav: dev_unreal_8          
# Unreal Engine 
  - scope:
      path: "_unreal-engine"
      type: unreal-engine
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true      
# Computação Gráfica
  - scope:
      path: "_computacao-grafica"
      type: computacao-grafica
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true 
      sort_by: order      
      category: "Desenvolvimento de jogos digitais"
      sidebar:
        nav: dev_computacao                     
# A taberna do pônei saltitante
  - scope:
      path: "_a-taberna-do-ponei-saltitante"
      type: a-taberna-do-ponei-saltitante
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true 
      sort_by: order      
      category: "Desenvolvimento de jogos digitais"                                
      sidebar:
        nav: banco_dados
# Modelagem 3D
  - scope:
      path: "_modelagem-3d"
      type: modelagem-3d
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true 
      sort_by: order      
      category: "Desenvolvimento de jogos digitais"                                
      sidebar:
        nav: dev_modelagem3d
# Jogos Digitais
  - scope:
      path: "_jogos-digitais"
      type: jogos-digitais
    values:
      layout: single
      read_time: true      
      author_profile: false
      share: true 
      show_date: true
      toc: true 
      sort_by: order      
      category: "Desenvolvimento de jogos digitais"                  
      sidebar:
        nav: dev_game



