theme: jekyll-theme-cayman
title: CafeGeek
description: O CafeGeek é um site educacional com foco em desenvolvimento de jogos digitais e as disciplinas que orbitam este fantástico mundo.
author: CafeGeek

includes_dir  : _include
include       : _include


# --- Web Analytics Section --- #
gtag: "UA-74199518-1"
google_analytics: UA-74199518-1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
