theme: jekyll-theme-cayman
author: CafeGeek

includes_dir  : _include
include       : _include

github:
  is_project_page: false

# --- Web Analytics Section --- #
gtag: "UA-74199518-1"
google_analytics: UA-74199518-1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
