theme: jekyll-theme-dinky
title: CafeGeek
description: O CafeGeek é um site educacional com foco em desenvolvimento de jogos digitais e as disciplinas que orbitam este fantástico mundo.
author: CafeGeek

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/imagens/cafegeek_small.png"
title-img: /imagens/cafegeek_small.png

social-network-links:
  email: "someone@example.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: c/daattali

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

google_analytics_tracking_id: 256152900

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
