theme: jekyll-theme-cayman
title: CafeGeek
description: O CafeGeek é um site educacional com foco em desenvolvimento de jogos digitais e as disciplinas que orbitam este fantástico mundo.
author: CafeGeek

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

include: _include

social-network-links:
  email: "someone@example.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: c/daattali

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

# --- Web Analytics Section --- #
gtag: "UA-74199518-1"
google_analytics: UA-74199518-1

url: "https://myerco.github.io/CafeGeek/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
